apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.web.ingress.host }}
spec:
  secretName: {{ .Values.web.ingress.host }}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: certs
    kind: ClusterIssuer
  dnsNames:
  - {{ .Values.web.ingress.host }}