apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.web.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "web.fullname" . }}
spec:
  rules:
  - host: {{ .Values.web.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-{{ .Chart.Name }}-{{ .Values.web.name }}
            port: 
              number: {{ .Values.web.servicePort }}
      - path: /api/v1/streaming
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-{{ .Chart.Name }}-{{ .Values.streaming.name }}
            port: 
              number: {{ .Values.streaming.servicePort }}
  tls:
    - secretName: {{ .Values.web.ingress.host }}
      hosts:
      - {{ .Values.web.ingress.host }}
